server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  # 如果你希望代理 API 请求也可以添加如下内容
  # location /api/ {
  #   proxy_pass http://backend:3000;
  # }
}
